version: "3.8"

services:
  db-master:
    container_name: mysql_master
    build: 
      context: .
      dockerfile: master/Dockerfile
    restart: always
    deploy:
      replicas: 1
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - db-master:/var/lib/mysql
      - db-master:/var/lib/mysql-files
    networks:
      - appnet
  
  db-slave:
    container_name: mysql_slave
    build: 
      context: .
      dockerfile: slave/Dockerfile
    restart: always
    deploy:
      replicas: 1
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - db-slave:/var/lib/mysql
      - db-slave:/var/lib/mysql-files
    networks:
      - appnet
  
# Names our volume
volumes:
  db-master:
  db-slave: 

networks:
  appnet:
    driver: overlay
